export const ANIMATION_RESET = ["Idleloop", "idle_breatheloop", "Idle_Swayloop"];

export const AVATAR_ANIMATIONS = [
  "GangnamStyle",
  "fusionL",
  "fusionR",
  "Generic_HandFan",
  "Generic_Lazy",
  "Generic_look_around",
  "Generic_Squat",
  "GenericLookAround",
  "Generic_Happy",
  "funnypose",
  "Excited_dance",
  "Emote_OrangeJusticeLoop",
  "Emote_KpopLoop",
  "Emote_InfiniDab_loop",
  "angelTaisou",
  "ArmWaveDanceloop",
  "Bellydancing",
  "chunibyou",
  "Dance_INTERNET_YAMEROloop",
  "Dance_Loli_Kami_Requiem",
  "Dance_monkeyloop",
  "Dance_washing",
  "graceful_dance",
  "HandpumpDanceloop",
  "HipHopDanceloop",
  "Humming",
  "LookAround",
  "LookingBehind",
  "ModelPose",
  "NervouslyLookAround",
  "pose_peace1",
  "Relax",
  "RumbaDanceloop",
  "SalsaDanceloop",
  "SambaDance1loop",
  "SambaDanceloop",
  "ShowFullBody",
  "ToothlessLoop",
];

export const CHAT_WIDGET_CONFIG = {
  mode: "realtime-widget",
  avatarUrl: "Botnoi",
  widgetId: "bothotel",
  greetingInstruction: "",
  enableBubble: "false",
  cameraOffset: "0,0,0.5",
  animationUrl: "Greeting",
  defaultAnimationUrl: "Idleloop, idle_breatheloop, Idle_Swayloop",
  randomGeneric: "false",
};
